name: GitHub Actions demo
on:
  push:
    branches:
    - main
    paths-ignore:
    - '.github/**'
  pull_request:
    branches: 
    - main
  schedule:
  - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: 'Environment to deploy to' 
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: "Info log"
      run: echo "event ${{ github.event_name}}, branch ${{github.ref}}"
      
    - uses: actions/checkout@v3.3.0

    - name: List files in the repository
      run: tree
      
  Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "Testing..."
      
  Load-Test:
    runs-on: ubuntu-latest    
    needs: Build
    environment: Load-Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: | 
          echo "Testing..."
          sleep 15
          
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.envrionment == 'Production'
    steps:
      - run: | 
          echo "Deploy step 1"
          sleep 10
      - run: | 
          echo "Deploy step 2"
          sleep 10
      - run: | 
          echo "Deploy step 3"
          sleep 10
      - run: | 
          echo "Deploy step 4"
          sleep 10
      - run: | 
          echo "Deploy step 5"
          sleep 10
  
        

